const express = require('express');
const rotas = require('../app/controller/livro-controller');

const app = express();

const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  //apis: ['../app/config/custom-express.js', './config/*.js', 'server.js'],
  apis: ['./src/app/controller/*.js'],
};

const specs = swaggerJsdoc(options);
const swaggerUi = require('swagger-ui-express');
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));

module.exports = app;

rotas(app);
